# Generated by Django 5.1.6 on 2025-02-23 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('idPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('nomPrueba', models.CharField(max_length=250)),
                ('nombre', models.BooleanField()),
                ('apellido1', models.BooleanField()),
                ('apellido2', models.BooleanField()),
                ('ano', models.BooleanField()),
                ('categoria', models.BooleanField()),
                ('club', models.BooleanField()),
                ('prueba1', models.BooleanField()),
                ('prueba2', models.BooleanField()),
                ('prueba3', models.BooleanField()),
                ('fechafin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('idAtleta', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('ape1', models.CharField(max_length=50)),
                ('ape2', models.CharField(max_length=50)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('categoria', models.CharField(blank=True, max_length=6, null=True)),
                ('club', models.CharField(blank=True, max_length=20, null=True)),
                ('prueba1', models.CharField(blank=True, max_length=30, null=True)),
                ('prueba2', models.CharField(blank=True, max_length=30, null=True)),
                ('prueba3', models.CharField(blank=True, max_length=30, null=True)),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incripApp.competicion')),
            ],
        ),
    ]
